backendServices:
  - name: DeviceMonitoringProject
    path: Backend/DeviceMonitoringProject
  - name: AlarmService
    path: Backend/AlarmService
  - name: GatewayService
    path: Backend/GatewayService/GatewayService

frontendProjects:
  - name: device_monitoring_frontend
    path: Frontend/device_monitoring_frontend
  - name: device-monitoring-viz
    path: Frontend/device-monitoring-viz

settings:
  backend:
    coverity: true
    sbom: true
  frontend:
    coverity: true
