frontendProjects:
  - name: device_monitoring_frontend
    path: Frontend/device_monitoring_frontend
  - name: device-monitoring-viz
    path: Frontend/device-monitoring-viz

settings:
  backend:
    folder_path: Backend
    sonar: true
    coverity: true
    coverity_project_name: "Device+Monitoring+Backends+Git"
    coverity_project_url_name: "device-monitoring-backends-git"
    sbom: true
  frontend:
    folder_path: Frontend
    sonar: false
    coverity: false
    coverity_project_name: "Device+Monitoring+Frontends+Git"
    coverity_project_url_name: "device-monitoring-frontends-git"
    sbom: false