    name: My First Pipeline # A name for your workflow, displayed in the Actions tab

    on: [push] # The event that triggers the workflow (e.g., push, pull_request)

    jobs:
      build: # Define a job named 'build'
        runs-on: ubuntu-latest # Specify the operating system for the job

        steps:
          - name: Checkout Code # Step to check out your repository's code
            uses: actions/checkout@v4

          - name: Run a simple command # A step to execute a shell command
            run: echo "Hello from GitHub Actions!"
