name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-generic:
    uses: PremalWonderbiz/Workflows/.github/workflows/generic-ci.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
      COVERITY_BACKEND_PROJECT_TOKEN: ${{ secrets.COVERITY_BACKEND_PROJECT_TOKEN }}  
      COVERITY_FRONTEND_PROJECT_TOKEN: ${{ secrets.COVERITY_FRONTEND_PROJECT_TOKEN }}  
    with:
      backend_sonar_key: "premalwonderbiz_DeviceMonitoringProject_Backend"
      frontend_sonar_key: "premalwonderbiz_DeviceMonitoringProject_Frontend"
      SONAR_HOST_URL: "https://sonarcloud.io"
      SONAR_ORG: "premalwonderbiz"
      COVERITY_EMAIL: "premal.kadam@wonderbiz.in"
