name: Sonar Analysis

on:
  workflow_dispatch:

jobs:
  sonar:
    uses: PremalWonderbiz/Workflows/.github/workflows/main-sequential-ci.yml@main
    with:
      sonarAnalysisFile: "Backend/SonarQube.Analysis.xml"
    secrets: inherit
